---
#
# Post deployment of appliance automation
#

- hosts: cfme-vmdb, cfme-worker
  gather_facts: false
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_ssh_pass: smartvm
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - sshkey

- hosts: cfme-vmdb
  gather_facts: true
  remote_user: root
  vars:
    config_type: cfme-vmdb
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - version
    - hostname
    - repos
    - { role: ntpd, when: is54}
    - { role: chronyd, when: (is55 or is56 or is57 or isMaster)}
    - { role: config-interface, when: "{{appliances[inventory_hostname].interfaces|length}} > 0" }
    - { role: proctitle-patch, when: is55}
    - { role: init-vmdb, when: not isdeployed }
    - { role: collectd, when: "{{appliances[inventory_hostname].run_collectd}} == true"}
    - { role: gem-statsd-ruby, when: "{{appliances[inventory_hostname].statsd_miqqueue_patch}} or {{appliances[inventory_hostname].statsd_uiworker_patch}}"}
    - { role: statsd-miqqueue-patch, when: "{{appliances[inventory_hostname].statsd_miqqueue_patch}} == true"}
    - { role: statsd-uiworker-patch, when: "{{appliances[inventory_hostname].statsd_uiworker_patch}} == true"}

- hosts: cfme-worker
  gather_facts: true
  remote_user: root
  vars:
    config_type: cfme-worker
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - version
    - hostname
    - repos
    - { role: ntpd, when: (is54)}
    - { role: chronyd, when: (is55 or is56)}
    - { role: config-interface, when: "{{appliances[inventory_hostname].interfaces|length}} > 0" }
    - { role: proctitle-patch, when: is55}
    - { role: external-vmdb, when: not isdeployed }
    - { role: collectd, when: "{{appliances[inventory_hostname].run_collectd}} == true"}
    - { role: gem-statsd-ruby, when: "{{appliances[inventory_hostname].statsd_miqqueue_patch}} or {{appliances[inventory_hostname].statsd_uiworker_patch}}"}
    - { role: statsd-miqqueue-patch, when: "{{appliances[inventory_hostname].statsd_miqqueue_patch}} == true"}
    - { role: statsd-uiworker-patch, when: "{{appliances[inventory_hostname].statsd_uiworker_patch}} == true"}
