---
#
# Role to determine version and set a fact with the CFME version
#

- name: Get version
  shell: cat /var/www/miq/vmdb/VERSION
  register: version_output
  changed_when: false

- name: Set fact for CFME version 5.4.x
  set_fact:
    is54: true
    is55: false
    is56: false
    is57: false
    isMaster: false
  when: version_output.stdout|match("^5.4.")

- name: Set fact for CFME version 5.5.x
  set_fact:
    is54: false
    is55: true
    is56: false
    is57: false
    isMaster: false
  when: version_output.stdout|match("^5.5.")

- name: Set fact for CFME version 5.6.x
  set_fact:
    is54: false
    is55: false
    is56: true
    is57: false
    isMaster: false
  when: version_output.stdout|match("^5.6.")

- name: Set fact for CFME version 5.7.x
  set_fact:
    is54: false
    is55: false
    is56: false
    is57: true
    isMaster: false
  when: version_output.stdout|match("^5.7.")

- name: Set fact for Upstream ManageIQ Master
  set_fact:
    is54: false
    is55: false
    is56: false
    is57: false
    isMaster: true
  when: version_output.stdout|match("^master")

- name: Determine if vmdb is configured
  stat: path=/var/www/miq/vmdb/GUID
  register: stat_guid

- name: Set fact isdeployed
  set_fact:
    isdeployed: "{{stat_guid.stat.exists}}"

# - debug: msg="is54={{is54}},is55={{is55}},is56={{is56}}"
