---
#
# Playbook to reset cfme appliance database
#

- hosts: cfme-vmdb,cfme-all-in-one
  gather_facts: false
  remote_user: root
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.local.yml
  roles:
    - version
    - reset-database
